<div class="container-fluid overflow-visible">
    <div class="row">
        <div class="col-lg-12 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h4>Déclaration de protection des données pour les exploitants de sites web conformément aux exigences de la loi fédérale suisse sur la protection des données (loi sur la protection des données - LPD)</h4>
                </div>
                <div class="card-body">
                    <h1 style="margin-top:12pt; margin-left:36pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:16pt;"><span style="font-family:'Calibri Light';">1.</span><span style="width:5.98pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp;&nbsp;</span><span style="font-family:'Calibri Light';">Identit&eacute; et coordonn&eacute;es du responsable</span></h1>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Le responsable au sens de la LPD est :</p>
                    <p style="margin-top:0pt; margin-bottom:0pt;">Association Ch&oelig;ur &agrave; C&oelig;ur</p>
                    <p style="margin-top:0pt; margin-bottom:0pt;">La tour 4</p>
                    <p style="margin-top:0pt; margin-bottom:0pt;">2735 B&eacute;vilard</p>
                    <p style="margin-top:0pt; margin-bottom:0pt;"><a href="mailto:contact@choeuracoeur-valbirse.ch" style="text-decoration:none;"><u><span style="color:#0563c1;">contact@choeuracoeur-valbirse.ch</span></u></a></p>
                    <h1 style="margin-top:12pt; margin-left:36pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:16pt;"><span style="font-family:'Calibri Light';">2.</span><span style="width:5.98pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp;&nbsp;</span><span style="font-family:'Calibri Light';">Acc&egrave;s au site web</span></h1>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><a name="_Toc121232531"><span style="font-family:'Calibri Light';">Description et &eacute;tendue du traitement des donn&eacute;es</span></a></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Lorsque vous acc&eacute;dez &agrave; notre site web, c&apos;est-&agrave;-dire m&ecirc;me si vous ne vous enregistrez pas ou ne transmettez pas d&apos;informations d&apos;une autre mani&egrave;re, des informations de nature g&eacute;n&eacute;rale sont automatiquement collect&eacute;es. Ces informations (fichiers journaux du serveur) comprennent par exemple le type de navigateur web, le syst&egrave;me d&apos;exploitation utilis&eacute;, le nom de votre fournisseur de services Internet, votre adresse IP, l&apos;URL de r&eacute;f&eacute;rence, la date et l&apos;heure d&apos;acc&egrave;s et d&apos;autres informations similaires. Elles sont notamment trait&eacute;es aux fins suivantes :</p>
                    <ol type="1" class="awlist1" style="margin:0pt; padding-left:0pt;">
                        <li style="margin-left:36pt;"><span style="width:9.09pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp;&nbsp;</span>Assurer une connexion sans probl&egrave;me du site web,</li>
                        <li style="margin-left:36pt;"><span style="width:9.09pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp;&nbsp;</span>Assurer le bon fonctionnement de notre site web,</li>
                        <li style="margin-left:36pt; margin-bottom:8pt;"><span style="width:9.09pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp;&nbsp;</span>Assurer et &eacute;valuer la s&eacute;curit&eacute; et la stabilit&eacute; du syst&egrave;me, en particulier pour d&eacute;tecter les abus.</li>
                    </ol>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Ces donn&eacute;es sont &eacute;galement enregistr&eacute;es dans les fichiers journaux de notre syst&egrave;me. Ces donn&eacute;es ne sont pas enregistr&eacute;es avec d&apos;autres donn&eacute;es personnelles de l&apos;utilisateur. Nous n&apos;utilisons pas vos donn&eacute;es pour tirer des conclusions sur votre personne. Nous nous r&eacute;servons toutefois le droit de v&eacute;rifier ult&eacute;rieurement les fichiers journaux du serveur si des indices concrets devaient indiquer une utilisation ill&eacute;gale.</p>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><span style="font-family:'Calibri Light';">Destination des donn&eacute;es</span></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Pour l&apos;exploitation et la maintenance de notre site web, nous faisons appel &agrave; des prestataires de services qui agissent en tant que nos sous-traitants. Tous les prestataires de services sont tenus par contrat de traiter vos donn&eacute;es de mani&egrave;re confidentielle.</p>
                    <h1 style="margin-top:12pt; margin-left:36pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:16pt;"><span style="font-family:'Calibri Light';">3.</span><span style="width:5.98pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp;&nbsp;</span><span style="font-family:'Calibri Light';">Bulletin d&apos;information</span></h1>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><a name="_Toc121232539"><span style="font-family:'Calibri Light';">Description et &eacute;tendue du traitement des donn&eacute;es</span></a></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Vos donn&eacute;es sont utilis&eacute;es exclusivement pour vous envoyer par e-mail la newsletter que vous recevrez automatiquement en tant que membre, pour &eacute;valuer la mani&egrave;re dont vous utilisez la newsletter et, le cas &eacute;ch&eacute;ant, les contenus qui y sont li&eacute;s. L&apos;indication de votre nom permet de s&apos;adresser personnellement &agrave; vous dans la newsletter et, le cas &eacute;ch&eacute;ant, de vous identifier si vous souhaitez faire usage de vos droits en tant que personne concern&eacute;e.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Les donn&eacute;es suivantes sont enregistr&eacute;es&nbsp;:</p>
                    <ol type="1" class="awlist2" style="margin:0pt; padding-left:0pt;">
                        <li style="margin-left:36pt;"><span style="width:9.09pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp;&nbsp;</span>Nom et Pr&eacute;nom</li>
                        <li style="margin-left:36pt;"><span style="width:9.09pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp;&nbsp;</span>Adresse &eacute;lectronique</li>
                    </ol>
                    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:6pt;">De plus, nous analysons votre comportement de lecture et d&apos;utilisation afin d&apos;am&eacute;liorer constamment notre newsletter et de v&eacute;rifier la bonne r&eacute;ception de cette derni&egrave;re. Pour ce faire, nous analysons si vous recevez et lisez nos newsletters.</p>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><span style="font-family:'Calibri Light';">Destinataire des donn&eacute;es</span></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Pour l&apos;envoi et l&apos;analyse des donn&eacute;es, nous faisons appel &agrave; des prestataires de services qui agissent en tant que sous-traitants. Tous les prestataires de services sont tenus par contrat de traiter vos donn&eacute;es de mani&egrave;re confidentielle.</p>
                    <h1 style="margin-top:12pt; margin-left:36pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:16pt;"><span style="font-family:'Calibri Light';">4.</span><span style="width:5.98pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp;&nbsp;</span><span style="font-family:'Calibri Light';">Utilisation des cookies</span></h1>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><a name="_Toc121232555"><span style="font-family:'Calibri Light';">Description et &eacute;tendue du traitement des donn&eacute;es</span></a></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Un cookie est un petit ensemble de donn&eacute;es qui est cr&eacute;&eacute; lors de la visite d&apos;un site web et qui est stock&eacute; temporairement sur le syst&egrave;me de l&apos;utilisateur. Si le serveur de ce site web est &agrave; nouveau appel&eacute; par ce syst&egrave;me, le navigateur renvoie le cookie re&ccedil;u pr&eacute;c&eacute;demment au serveur. Le serveur peut &eacute;valuer les informations obtenues par cette proc&eacute;dure. Les cookies permettent notamment de faciliter la navigation sur un site web.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Les cookies contribuent &agrave; rendre un site web utilisable en permettant des fonctions de base telles que la navigation sur le site et l&apos;acc&egrave;s &agrave; des zones s&eacute;curis&eacute;es du site.</p>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><span style="font-family:'Calibri Light';">Utilisation de cookies techniquement n&eacute;cessaires</span></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Certaines fonctions de notre site Internet ne peuvent pas &ecirc;tre propos&eacute;es sans l&apos;utilisation de cookies. Pour celles-ci, il est n&eacute;cessaire que le navigateur soit reconnu m&ecirc;me apr&egrave;s un changement de page.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Nous utilisons des cookies aux fins suivantes :</p>
                    <ol type="1" class="awlist3" style="margin:0pt; padding-left:0pt;">
                        <li style="margin-left:36pt; margin-bottom:8pt;"><span style="width:9.09pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp;&nbsp;</span>Information de connexion</li>
                    </ol>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Les donn&eacute;es suivantes sont alors enregistr&eacute;es et transmises dans les cookies :</p>
                    <ol type="1" class="awlist4" style="margin:0pt; padding-left:0pt;">
                        <li style="margin-left:36pt; margin-bottom:8pt;"><span style="width:9.09pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp;&nbsp;</span>Token d&rsquo;authentification</li>
                    </ol>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><span style="font-family:'Calibri Light';">Utilisation de cookies non n&eacute;cessaires d&rsquo;un point de vue technique</span></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Nous utilisons &eacute;galement sur le site web des cookies qui permettent d&apos;analyser le comportement de navigation des utilisateurs. Ces cookies sont utilis&eacute;s pour rendre l&apos;utilisation du site web plus efficace et plus attrayante. Nous utilisons les technologies d&apos;analyse web des fournisseurs suivants :</p>
                    <ol type="1" class="awlist5" style="margin:0pt; padding-left:0pt;">
                        <li style="margin-left:36pt; margin-bottom:8pt;"><span style="width:9.09pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp;&nbsp;</span>Matomo</li>
                    </ol>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><span style="font-family:'Calibri Light';">Destination des donn&eacute;es</span></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Pour l&apos;exploitation et la maintenance de notre site web, nous faisons appel &agrave; des prestataires de services techniques qui agissent en tant que nos sous-traitants.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Vous trouverez d&apos;autres destinataires et des d&eacute;tails sur le fonctionnement technique des outils utilis&eacute;s et des informations sur la mani&egrave;re d&apos;emp&ecirc;cher la transmission de donn&eacute;es (tracking) dans le chapitre &quot;Outils d&apos;analyse&quot;.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Tous les prestataires de services sont tenus par contrat de traiter vos donn&eacute;es de mani&egrave;re confidentielle.</p>
                    <h1 style="margin-top:12pt; margin-left:36pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:16pt;"><span style="font-family:'Calibri Light';">5.</span><span style="width:5.98pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp;&nbsp;</span><span style="font-family:'Calibri Light';">Analyse du comportement</span></h1>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><span style="font-family:'Calibri Light';">Description et &eacute;tendue du traitement des donn&eacute;es</span></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Nous &eacute;valuons le comportement des utilisateurs &agrave; l&apos;aide d&apos;outils d&apos;analyse. Vous trouverez une description plus d&eacute;taill&eacute;e de ces outils dans le chapitre &quot;Outils d&apos;analyse&quot; de la pr&eacute;sente d&eacute;claration de protection des donn&eacute;es.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Le traitement est effectu&eacute; sur la base de notre int&eacute;r&ecirc;t l&eacute;gitime. La mesure de la port&eacute;e et les informations qui en d&eacute;coulent sont appropri&eacute;es pour adapter les fonctionnalit&eacute;s offertes par notre site web.</p>
                    <h2 style="margin-top:2pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:13pt;"><span style="font-family:'Calibri Light';">Destination des donn&eacute;es</span></h2>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Pour l&apos;exploitation et la maintenance de notre site web, nous faisons appel &agrave; des prestataires de services techniques qui agissent en tant que nos sous-traitants. Tous les prestataires de services sont tenus par contrat de traiter vos donn&eacute;es de mani&egrave;re confidentielle.</p>
                    <h1 style="margin-top:12pt; margin-left:36pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:16pt;"><span style="font-family:'Calibri Light';">6.</span><span style="width:5.98pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp;&nbsp;</span><span style="font-family:'Calibri Light';">Outil d&rsquo;analyse utilis&eacute;s</span></h1>
                    <p style="margin-top:6pt; margin-bottom:6pt;">Ce site web utilise Matomo (anciennement Piwik), un logiciel open source pour l&apos;&eacute;valuation statistique de l&apos;acc&egrave;s des visiteurs. Le fournisseur du logiciel Matomo est la soci&eacute;t&eacute; InnoCraft Ltd, 150 Willis St, 6011 Wellington, Nouvelle-Z&eacute;lande.</p>
                    <p style="margin-top:6pt; margin-bottom:6pt;">Matomo utilise des cookies qui permettent d&apos;analyser l&apos;utilisation que vous faites du site web. Les informations g&eacute;n&eacute;r&eacute;es par le cookie concernant votre utilisation des fonctionnalit&eacute;s du site web sont enregistr&eacute;es sur un serveur en Suisse. Nous avons configur&eacute; Matomo de mani&egrave;re &agrave; ce qu&apos;aucun profilage ne soit effectu&eacute;.</p>
                    <p style="margin-top:6pt; margin-bottom:6pt;">L&apos;adresse IP est anonymis&eacute;e imm&eacute;diatement apr&egrave;s le traitement et avant son stockage, en tronquant les deux derniers octets. Vous avez la possibilit&eacute; d&apos;emp&ecirc;cher l&apos;installation des cookies en modifiant les param&egrave;tres de votre logiciel de navigation. Nous attirons votre attention sur le fait qu&apos;en cas de r&eacute;glage correspondant, il se peut que vous ne puissiez plus utiliser toutes les fonctions de ce site web.</p>
                    <p style="margin-top:6pt; margin-bottom:6pt;">Vous trouverez de plus amples informations sur les param&egrave;tres de confidentialit&eacute; du logiciel Matomo en cliquant sur le lien suivant : https://matomo.org/docs/privacy/.</p>
                    <p style="margin-top:6pt; margin-bottom:6pt;">Les donn&eacute;es sont effac&eacute;es d&egrave;s qu&apos;elles ne sont plus n&eacute;cessaires &agrave; nos fins d&apos;enregistrement. Dans notre cas, cela se fait de mani&egrave;re automatis&eacute;e sur apr&egrave;s 6 mois.</p>
                    <p style="margin-top:6pt; margin-bottom:6pt;">Vous pouvez vous opposer au traitement des donn&eacute;es par Matomo de trois mani&egrave;res diff&eacute;rentes : Premi&egrave;rement, vous pouvez emp&ecirc;cher compl&egrave;tement le d&eacute;p&ocirc;t de cookies dans votre navigateur. Toutefois, cela peut vous emp&ecirc;cher d&apos;utiliser certaines fonctions de notre site web qui n&eacute;cessitent une identification. D&apos;autre part, vous pouvez activer le param&egrave;tre &quot;Do-not-Track&quot; dans votre navigateur. Nous avons configur&eacute; Matomo de mani&egrave;re &agrave; ce qu&apos;il respecte ce param&egrave;tre. De plus, vous pouvez cr&eacute;er un cookie dit &quot;opt-out&quot; en cliquant ci-dessous, ce cookie &eacute;tant valable deux ans. Cela signifie que Matomo n&apos;enregistrera pas vos visites ult&eacute;rieures. Notez toutefois que le cookie opt-out sera supprim&eacute; si vous supprimez tous les cookies.</p>
                    <p style="margin-top:6pt; margin-bottom:6pt;">
                    <h1 style="margin-top:12pt; margin-left:36pt; margin-bottom:0pt; page-break-inside:avoid; page-break-after:avoid; line-height:108%; font-size:16pt;"><span style="font-family:'Calibri Light';">7.</span><span style="width:5.98pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp;&nbsp;</span><span style="font-family:'Calibri Light';">Droits de la personne concern&eacute;e</span></h1>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Vous disposez des droits suivants en ce qui concerne les donn&eacute;es personnelles vous concernant :</p>
                    <p style="margin-top:0pt; margin-left:53.25pt; margin-bottom:0pt; text-indent:-35.25pt;">&bull;<span style="width:29.77pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span>le droit d&apos;obtenir des informations sur les donn&eacute;es personnelles que nous conservons &agrave; votre sujet et sur la mani&egrave;re dont nous les traitons ;</p>
                    <p style="margin-top:0pt; margin-left:53.25pt; margin-bottom:0pt; text-indent:-35.25pt;">&bull;<span style="width:29.77pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span>le droit de recevoir une copie de vos donn&eacute;es personnelles dans un format courant ;</p>
                    <p style="margin-top:0pt; margin-left:53.25pt; margin-bottom:0pt; text-indent:-35.25pt;">&bull;<span style="width:29.77pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span>le droit de rectifier vos donn&eacute;es personnelles ;</p>
                    <p style="margin-top:0pt; margin-left:53.25pt; margin-bottom:0pt; text-indent:-35.25pt;">&bull;<span style="width:29.77pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span>le droit de demander la suppression de vos donn&eacute;es personnelles ;</p>
                    <p style="margin-top:0pt; margin-left:53.25pt; margin-bottom:8pt; text-indent:-35.25pt;">&bull;<span style="width:29.77pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span>le droit de vous opposer au traitement de vos donn&eacute;es personnelles.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Veuillez noter que des exceptions s&apos;appliquent &agrave; ces droits. Dans la mesure o&ugrave; la loi le permet, nous pouvons refuser votre demande d&apos;exercer ces droits.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Vous pouvez &agrave; tout moment r&eacute;voquer votre consentement au traitement de vos donn&eacute;es personnelles. Veuillez noter que la r&eacute;vocation n&apos;a d&apos;effet que pour l&apos;avenir. Les traitements effectu&eacute;s avant la r&eacute;vocation ne sont pas concern&eacute;s.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Pour obtenir des informations sur les donn&eacute;es personnelles que nous traitons, veuillez envoyer votre demande de renseignements &agrave; contact@choeuracoeur-valbirse.ch.</p>
                    <p style="margin-top:0pt; margin-bottom:8pt;">Vous avez en outre le droit de d&eacute;poser une plainte aupr&egrave;s du Pr&eacute;pos&eacute; f&eacute;d&eacute;ral &agrave; la protection des donn&eacute;es et &agrave; la transparence (PFPDT).</p>

                    <div id="matomo-opt-out"></div>
                    <script src="https://matomo.host-free.ch/index.php?module=CoreAdminHome&action=optOutJS&divId=matomo-opt-out&language=auto&showIntro=1"></script>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>